#!/bin/bash
set -e

# Variables
DB_HOST=$DB_PORT_5432_TCP_ADDR
DB_NAME=${DB_NAME:-sonar}
DB_USER=${DB_USER:-sonar}
DB_PASS=${DB_PASS:-xaexohquaetiesoo}

cp -rf /sonar/conf /opt/sonar/

# Configure wrapper.conf
sed -i 's|#wrapper.java.additional.6=-server|wrapper.java.additional.6=-server|g' /opt/sonar/conf/wrapper.conf

# Configure sonar.properties
sed -i 's|#sonar.jdbc.username=sonar|sonar.jdbc.username='"${DB_USER}"'|g' /opt/sonar/conf/sonar.properties
sed -i 's|#sonar.jdbc.password=sonar|sonar.jdbc.password='"${DB_PASS}"'|g' /opt/sonar/conf/sonar.properties
sed -i 's|sonar.jdbc.url=jdbc:h2|#sonar.jdbc.url=jdbc:h2|g' /opt/sonar/conf/sonar.properties
sed -i 's|#sonar.jdbc.url=jdbc:postgresql://localhost/sonar|sonar.jdbc.url=jdbc:postgresql://'"${DB_HOST}"'/'"${DB_NAME}"'|g' /opt/sonar/conf/sonar.properties

# Configure http proxy
if [ -n "${HTTP_PROXY_HOST}" ]; then
  sed -i 's|#http.proxyHost=|http.proxyHost='"${HTTP_PROXY_HOST}"'|g' /opt/sonar/conf/sonar.properties
  sed -i 's|#http.proxyPort=|http.proxyPort='"${HTTP_PROXY_PORT}"'|g' /opt/sonar/conf/sonar.properties  
fi  

appStart () {
  echo "Starting sonar..."
  set +e
  exec /opt/sonar/bin/linux-x86-64/sonar.sh console
  #/opt/sonar/bin/linux-x86-64/sonar.sh start
  #tail -f /opt/sonar/logs/sonar.log
}

appStop () {
  echo "Stoping sonar..."
  set +e
  echo parameters $@
  exec /opt/sonar/bin/linux-x86-64/sonar.sh stop
}

case "$1" in
  'start')
    appStart
    ;;
  'stop')
    appStop
    ;;
  *)
    appStart
    ;;
esac

exit 0
